# generated by clj2nix-1.0.4
{ pkgs ? import <nixpkgs> {} }:
  
  let repos = [
        "https://repo.clojars.org/"
        "https://repo1.maven.org/"
        "http://central.maven.org/maven2/"
        "http://oss.sonatype.org/content/repositories/releases/"
        "http://oss.sonatype.org/content/repositories/public/"
        "http://repo.typesafe.com/typesafe/releases/"
      ];

  in rec {
      makePaths = {extraClasspaths ? []}: (builtins.map (dep: if builtins.hasAttr "jar" dep.path then dep.path.jar else dep.path) packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});

      packages = [
  {
    name = "org.clojure/clojure";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "741b37171bda8365fe7831474b696dc9e5f4e254338d58e6d0155ea1b9af292e5b8d2ed6a8a8a6fc6983771266e47e2cb3c65e40e81fd27a6ad2ac3d37195fe3";
      version = "1.10.0";
    };
  }

  {
    name = "com.dropbox.core/dropbox-core-sdk";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "dropbox-core-sdk";
      groupId = "com.dropbox.core";
      sha512 = "bc1afd2a6949a6c2a8b829970e36d968b0da81f948d24b572b243c51a2fdf10bced29c048402937139fa8b8468e27db536b91c3e485db35cf3d21c33320134c9";
      version = "3.1.4";
    };
  }

  {
    name = "org.clojure/spec.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "18c97fb2b74c0bc2ff4f6dc722a3edec539f882ee85d0addf22bbf7e6fe02605d63f40c2b8a2905868ccd6f96cfc36a65f5fb70ddac31c6ec93da228a456edbd";
      version = "0.2.176";
    };
  }

  {
    name = "org.clojure/core.specs.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "348c0ea0911bc0dcb08655e61b97ba040649b4b46c32a62aa84d0c29c245a8af5c16d44a4fa5455d6ab076f4bb5bbbe1ad3064a7befe583f13aeb9e32a169bf4";
      version = "0.2.44";
    };
  }

  {
    name = "com.fasterxml.jackson.core/jackson-core";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "ebff4692c80aea8be13fccb999610e616d08b9f77513f72ec4d1f320d7e02fc9be06f5e4e228ec9745650544e3d3c8e24c97640dbc15692d49b1569f562aee58";
      version = "2.7.4";
    };
  }

  ];
  }
  